
var jobs = [
  {
    "title":"ISRO IS HIRING: SCIENTIST/ ENGINEER",
    "company":"ISRO",
    "location":"",
    "experience":"Freshers",
    "qualifications":"BE/ B.Tech or equivalent in Electronics & Communication Engineering with an aggregate minimum of 65% marks or CGPA 6.84/10.BE/ B.Tech or equivalent in Mechanical Engineering with an aggregate minimum of 65% marks or CGPA 6.84/10.BE/ B.Tech or equivalent in Computer Science Engineering with an aggregate minimum of 65% marks or CGPA 6.84/10. Age limit: 28 years",
    "description":"How to apply : Candidates may apply for multiple posts, subject to conditions. However, candidates applying for multiple posts should select common (same) written test centres. Candidates have to make application fee payment separately for applications for all the posts. The application for on-line registration will be hosted in the ISRO website between 25.05.2023 and 14.06.2023. Applications will be received on-line only. Upon registration, applicants will be provided with an on-line Registration Number, which should be carefully preserved for future reference. E-mail ID of the applicant is to be given in the application compulsorily. The last date for submitting on-line application is 14.06.2023.",
    "logo":"./img/companies/isro.png",
    "applyLink":"https://apps.ursc.gov.in/CentralBE-2023/advt.jsp",
    "salary":"",
    "skills":"",
    "responsibilities":""

  },
  {
    "title": "Java Developer",
    "company": "Tata Consultancy Services (TCS)",
    "location": "Hyderabad/Secunderabad, Chennai, Bangalore/ Bengaluru,Karnataka",
    "experience": "2 - 7 years",
    "description": "Job description Role : JAVA Developer Required Technical Skill Set**\r\nHands on experience on Java Spring boot MicroservicesAnalyze and evaluate the requirementGood understanding on frameworksGood understanding of MicroservicesGood analytical skills to assess the technical impactDesign the functional flowCoordinate  with business & other workstream stakeholders Desired Experience Range**\r\nTotal 2+ Yrs. of experience. Location of Requirement \r\nPan IndiaRole: Software Development - Other,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: Software DevelopmentEducationUG: Any GraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillsjavaspring bootspring mvc",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "logo": "./img/companies/tcs/TCS-1.jpg",
    "applyLink": "https://www.naukri.com/job-listings-java-developer-tata-consultancy-services-tcs-hyderabad-secunderabad-chennai-bangalore-bengaluru-karnataka-2-to-7-years-250523008875"
  
  },
  {
    "title": "Big Data Administrator",
    "company": "Tata Consultancy Services (TCS)",
    "location": "Kolkata, Hyderabad/Secunderabad, Chennai, Bangalore/Bengaluru",
    "experience": "4 - 8 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": " Must Have\r\n  1.Big Data Administrator with Infra experience (Hadoop / Cloudera)\r\n  2.Performance tuning of Hadoop clusters/ Upgrades\r\n  \r\n Good to Have\r\n  • 3+ years of experience in Scala development\r\n  • 3+ Python Scripting\r\n  • GIT Knowledge is required\r\n  • Knowledge of ELK stack and their plugins\r\n  • Knowledge on JSON\r\n  • Play-framework or similar kind of any framework experience like MVC/jQuery.\r\n  • Experiencing in using/maintaining the APIs \r\n\r\n\r\n\r\nRole: Data Engineer,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: Software DevelopmentEducationUG: Any GraduatePG: Any PostgraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillsBig Data Administration",
    "logo": "./img/companies/tcs/TCS-1.jpg",
    "applyLink": "https://www.naukri.com/job-listings-big-data-administrator-tata-consultancy-services-tcs-kolkata-hyderabad-secunderabad-chennai-bangalore-bengaluru-4-to-8-years-250523004808"
  },
  {
    "title": "Cognizant Technology Solution is hiring For Pyspark",
    "company": "Cognizant",
    "location": "Hyderabad/ Secunderabad,Telangana, Pune,Maharashtra, Gurgaon/ Gurugram,Haryana, Chennai,Tamil Nadu, Bangalore/ Bengaluru,Karnataka",
    "experience": "4 - 9 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "PysparkRole: DeveloperDesired Experience Range: 4 to 9 yearsLocation: Chennai/Bangalore/Pune/Hyderabad/Gurgoan Notice period : Immediate- 90 Days COGNIZANT AIA PRACTICE:Cognizants AI & Analytics practice helps our clients imagine and build the Digital Economy. We are recognized by Forrester, Gartner and by other leading analyst firms as a Leader in Data and AI technologies and services, citing us as the right partner to help create a business running on AI. We do this by bringing together human insight, digital strategy, industry knowledge, design thinking, and the latest technologies to create new experiences and launch new business models.\r\n Roles & Responsibilities :\r\n The developer must have sound knowledge in Apache Spark and Python programming.Experience should be 4-6 yearsDeep experience in developing data transforming and processing tasks using pySpark such as reading data from external sources, merge data, perform data enrichment      and load in to target data destinations.Developer must have  strong experience with Hadoop technologies.Developer also needs to have hands on experience in RDBMS.Developer also needs to have  hands on experience in the shell-scripting.The Developer also needs able to do the maintenance activity like fixing the bugs by analyzing it and able to maintain the jobs flow smooth.Experience in working in the SAFe/agile model is added advantage  Benefits:Exposure to new processes and technologies.Competitive salary at par with the best in the industry.Flexible and employee friendly environment.Interested Candidates apply here :  https://forms.office.com/r/mfNYkH84X3\r\n\r\n\r\n\r\nRole: Software Development - Other,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: Software DevelopmentEducationUG: Any GraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillspyspark",
    "logo": "./img/companies/cognigent/th.jpg",
    "applyLink": "https://www.naukri.com/job-listings-cognizant-technology-solution-is-hiring-for-pyspark-cognizant-hyderabad-secunderabad-telangana-pune-maharashtra-gurgaon-gurugram-haryana-chennai-tamil-nadu-bangalore-bengaluru-karnataka-4-to-9-years-190523007797"
  },
   {
    "title": "Senior Ms Sql Database Administrator",
    "company": "Tata Consultancy Services (TCS)",
    "location": "Kolkata, Hyderabad/Secunderabad, Chennai, Bangalore/ Bengaluru,Karnataka",
    "experience": "7 - 12 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "MSSQL Server: Expert in MSSQL 2014, 2016, 2019   internals.In-depth knowledge and expertise on High   Availability/DR/ReplicationExpertise in Design, Capacity   planning and provide strategic HA\\DR solutions based on Business requirement.   Hands-on and expertise on build the   DB migration, DB upgrade and Patching.Backup and Recovery, implement SSL   encryption, TDE and good knowledge on Access management.  Expertise on database performance   analysis and troubleshooting. Responsible for Query tuning and   preventative maintenance.Expertise in Automation using tools   like (PowerShell, Puppet, Python, shell scripting, Git, REST APIs etc)Knowledge & Hands-on Experience of   Cloud Databases (AWS Preferred).DevOps Knowledge.PostgreSQLExpertise in   PostgreSQL\\Aurora database Administration (On-Prem\\AWS)Good knowledge   on Administering AWS RDS databases and databases hosted on EC2.Expertise in Design, Capacity   planning and provide strategic HA\\DR solutions based on Business requirement.   Performance analysis and troubleshooting.Experience in implementing HA\\DR\\replication,   failover and troubleshooting replication lags. Expertise in installation, Upgrade,   and patching. Backup and RecoveryHands-on in   implementing Database monitoring using shell\\Perl scripts and using tool like   Datadog. \r\n\r\n\r\n\r\nRole: Database Administrator,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: DBA / Data warehousingEducationUG: Any GraduatePG: Any PostgraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillsMSSQL DBAReplicationPerformance Tuning",
    "logo": "./img/companies/tcs/TCS-1.jpg",
    "applyLink": "https://www.naukri.com/job-listings-senior-ms-sql-database-administrator-tata-consultancy-services-tcs-kolkata-hyderabad-secunderabad-chennai-bangalore-bengaluru-karnataka-7-to-12-years-250523005387"
  },
  {
    "title": "java developer|| 5 - 8 years|| joiner||Bangalore||Hyderabad||",
    "company": "HCLTech",
    "location": "Hyderabad/Secunderabad, Bangalore/Bengaluru",
    "experience": "5 - 8 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "Job descriptionRoles and Responsibilities \r\n Core Java 8 concepts, Spring Core, Spring MVC, Spring Boot, REST API, JSON, XML, SQL, Web Server \r\n\r\nRole: Back End Developer,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: Software DevelopmentEducationUG: Any GraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillsspring bootjavaspring mvcweb technologiesweb server",
    "logo": "./img/companies/hcl/hcl.jpg",
    "applyLink": "https://www.naukri.com/job-listings-java-developer-5-8-years-joiner-bangalore-hyderabad-hcltech-hyderabad-secunderabad-bangalore-bengaluru-5-to-8-years-260323001640"
  },
  {
    "title": "Data Bricks AWS Cloud",
    "company": "Tata Consultancy Services (TCS)",
    "location": "Hyderabad/Secunderabad, Chennai, Bangalore/Bengaluru",
    "experience": "3 - 7 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "Job descriptionGreetings from TATA CONSULTANCY SERVICES LIMITED!!! \r\nTCS has been a great pioneer in feeding the fire of young techies like you. We are a global leader in the technology arena and there is nothing that can stop us from growing together.\r\nRequired Skill Set 4+ years of experience working with AWS Cloud , Big Data Technologies, Data Bricks AWS Cloud Data Services  RedShift, Lambda , Glue etMust-Have:\r\nExperience with Design, build and operationalize enterprise data solutions and applications using one or more of AWS data and analytics services -RedShift, Kinesis, Lambda, Glue  Design and build production data pipelines from ingestion to consumption within a big data architecture.Design and implement data engineering, ingestion and curation functions on AWS cloud using AWS native or custom programming.Extensive experience working with Data warehousing requirements on AWS cloud platforms Experience with solutioning and designing Data warehousing solution on AWS cloud platform\r\nGood-to-Have:\r\nExp with ETL Tools – Informatica etc.Experience with Data modelling and Data analysis on AWS platform \r\n Experience Range: 4 to 7 Years Location: Minimum Qualification:15 years of full-time educationMinimum percentile of 50% in 10th, 12th, UG & PG (if applicable)Interested professionals can share their updated CV & the below details at swati.sanjagiri@tcs.comKindly fill in the below details:\r\nTotal Experience:Relevant Experience: Current CTC.:Expected CTC.: Notice Period: Current Location:Preferred location: Current org & previous org: Highest Qualification: University Name: Career Gap: Interview date & Timing:Mobile NO: \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n \r\n\r\n \r\n\r\n \r\n \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n \r\n\r\n \r\n\r\n \r\n \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n \r\n \r\n\r\nRole: IT & Information Security - Other,Industry Type: IT Services & Consulting,Department: IT & Information Security,Employment Type: Full Time, PermanentRole Category: IT & Information Security - OtherEducationUG: Any GraduatePG: Any PostgraduateDoctorate: Any DoctorateKey SkillsGlueBig Data Technologies",
    "logo": "./img/companies/tcs/TCS-1.jpg",
    "applyLink": "https://www.naukri.com/job-listings-data-bricks-aws-cloud-tata-consultancy-services-tcs-hyderabad-secunderabad-chennai-bangalore-bengaluru-3-to-7-years-250523007269"
  },
  
  {
    "title": "Application Support Engineer",
    "company": "Tata Consultancy Services (TCS)",
    "location": "Kolkata, Hyderabad/Secunderabad, Chennai, Bangalore/ Bengaluru,Karnataka",
    "experience": "4 - 7 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "Job description\r\nJob Description\r\n \r\n\r\nSkill Set :  Application Support, Linux, Scripting, Basics of Networking, ITIL (Incident, Change, Problem Management) \r\nMust-Have \r\nLinux knowledgeSNOW ITIL Processes (Incident/Change/Problem Management)Application Support experienceInfrastructure Support/Operations SupportServer MonitoringExcellent Communication skills\r\n\r\nGood-to-Have\r\nBasics of networkingScripting Bash/ShellAutomation knowledge \r\nRole: IT Support - Other,Industry Type: IT Services & Consulting,Department: IT & Information Security,Employment Type: Full Time, PermanentRole Category: IT SupportEducationUG: Any GraduatePG: Any PostgraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillsapplication supportitil processeslinux",
    "logo": "./img/companies/tcs/TCS-1.jpg",
    "applyLink": "https://www.naukri.com/job-listings-application-support-engineer-tata-consultancy-services-tcs-kolkata-hyderabad-secunderabad-chennai-bangalore-bengaluru-karnataka-4-to-7-years-250523005523"
  },


  {
    "title": "Maximo Technical Consultant-4-9Y- Bangalore-PWC SDC",
    "company": "PwC Service Delivery Center",
    "location": "Hyderabad/Secunderabad, Bangalore/Bengaluru",
    "experience": "4 - 9 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "We Have an urgent requirement for Maximo Technical in PWC SDC Bangalore Position: Maximo TechnicalLocation: Bangalore/Hyderabad/Mumbai/KolkataExperience: 4-9 YNotice Period: Immediate- 45 Days\r\nOverall around 4-5 years experience. Working knowledge of administration of Kubernetes or OpenShift Working knowledge of RDBMS Administration Building end to end WebSphere application server environments Experience in Installation, Configuration, Trouble-Shooting and performance tuning of IBM WebSphere Application Server ND WebSphere Fix Pack Upgrade, Certificate Management, Security Management Experience in installation and configuration of Directory Server Technical support to applications on troubleshooting Environment, software and application-level issues for WebSphere, Apache and IBM HTTP Server Excellent problem resolving interpersonal good communication skills with ability to work under pressure Design and Develop tools to standardize and automate monitoring, application support activities Good knowledge of Unix / Linux based systems and experience in performing Linux administration tasks Working knowledge of Azure cloud fundamentals is added advantage Working knowledge of Ansible, python, PHP is added advantage Working knowledge of scripting languages like unix shell and/or powershell is added advantage\r\nTotal Exp:Relevant Exp:CTCECTCCurrent CompanyNotice Period:Current LocationAre you okay with Bangalore location Yes/No?Exp in Maximo TechnicalExp in Kubernates OR OpenshiftExp in WebSphere application serverExp in RDBMSFlexible to work in different time zones Yes/NoInterested Candidates please share the CV on   dhamma.b.bhawsagar@pwc.comMB:8459621589\r\n\r\nRole: Back End Developer,Industry Type: Accounting / Auditing,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: Software DevelopmentEducationUG: Any Graduate, B.Tech/B.E. in Any Specialization, B.Sc in Any Specialization, BCA in Any SpecializationKey SkillsSkills highlighted with ‘‘ are preferred keyskillsMaximoMaximo IntegrationMaximo Technical",
    "logo": "./img/companies/pwc.jpg",
    "applyLink": "https://www.naukri.com/job-listings-maximo-technical-consultant-4-9y-bangalore-pwc-sdc-pwc-service-delivery-center-hyderabad-secunderabad-bangalore-bengaluru-4-to-9-years-250523008449"
  },
  {
    "title": "Software Developer",
    "company": "Teamlease Digital",
    "location": "Hyderabad/Secunderabad, Bangalore/Bengaluru",
    "experience": "4 - 9 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "Job descriptionHi,\r\nWe have requirement for one of our client for c2h role:Designation:Software DeveloperExp:3.5 to 8 YearsLocation:Bangalore,HyderabadSkills: MuleSoft Anypoint Platform, Apache Camel ,Swagger,Java,XML\r\nWork from office\r\nRegards,Ashwini.\r\nRole: Software Development - Other,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Part Time, Temporary/ContractualRole Category: Software DevelopmentEducationUG: Any GraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillsmulesoft anypointJavaxmlApache CamelMulesoft Anypoint Platform",
    "applyLink": "https://www.naukri.com/job-listings-software-developer-teamlease-digital-hyderabad-secunderabad-bangalore-bengaluru-4-to-9-years-250523009842"
  },
  {
    "title": "Sailpoint Developer",
    "company": "Tata Consultancy Services (TCS)",
    "location": "Hyderabad/Secunderabad, Bangalore/Bengaluru, Delhi / NCR",
    "experience": "4 - 9 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "Job descriptionDear Aspirant,\r\nGreetings from TCS !\r\nTCS presents Excellent Opportunities for  Sailpoint Developer / Senior Sailpoint Developer / Sailpoint Architect profile.\r\nExp: 2 Years - 15 Years\r\n\r\nJob Location: PAN India\r\n JOB DESCRIPTION: - Sailpoint Developer [ IIQ / IdentityNow ]\r\n Developing IIQ rules like Build Map Rule, Correlation Rule for on-boarding Applications.  Strong IAM domain and Java knowledge; and the ability to write scripts.  Developing Pre-Delegation Rule, Exclusion Rule and Advance Certification for Certifications.Experience in Bean Shell scripting / Powershell ScriptingExperience in Developing Web service connectors\r\nRegards,Sai Lokesh SRole: IT & Information Security - Other,Industry Type: IT Services & Consulting,Department: IT & Information Security,Employment Type: Full Time, PermanentRole Category: IT & Information Security - OtherEducationUG: Any GraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillsIiqjavasailpointIdentityiqjdbcidentity access managementSailpoint DeveloperBeanshellIDNiampowershellshell scriptingIdentityNow",
    "logo": "./img/companies/tcs/TCS-1.jpg",
    "applyLink": "https://www.naukri.com/job-listings-sailpoint-developer-tata-consultancy-services-tcs-hyderabad-secunderabad-bangalore-bengaluru-delhi-ncr-4-to-9-years-250523010107"
  },
  {
    "title": "Cards Tester V+ Professional",
    "company": "Synechron",
    "location": "Hyderabad/Secunderabad, Bangalore/Bengaluru",
    "experience": "4 - 7 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "Job description   - 4 to 7 year experienced associate with sound knowledge on cards domain \r\n - Should have good knowledge on testing concepts and lifecycle \r\n - Should have experience on requirement analysis, test planning and test execution \r\n -Should have good working knowledge on test and defect management tools \r\n - Should have good knowledge on testing deliverables        Tasks         Design & Build test harnesses for Functional Testing as SME.        Execute test cases and Support development of automated functional and regression pack and execute       Support automation of Test Data Management for Credit cards.       Design and develop the automated solution for Sanity testing for various repeatable tests.         Soft Skills:     Excellent communication and interpersonal skills   Ability to work well in a team environment   Strong attention to detail and ability to prioritize tasks effectively   Proactive, solution-oriented approach to problem-solving  Role: Quality Assurance and Testing - Other,Industry Type: Financial Services,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: Quality Assurance and TestingEducationUG: Any GraduatePG: Any PostgraduateKey SkillsAutomationSanity testingTest case executionInterpersonal skillsData managementFunctional testingTest executionCredit cardsDefect managementTesting",
    "applyLink": "https://www.naukri.com/job-listings-cards-tester-v-professional-synechron-hyderabad-secunderabad-bangalore-bengaluru-4-to-7-years-250523500813"
  },
  {
    "title": "Cards Tester V+",
    "company": "Synchron Infotech",
    "location": "Hyderabad/Secunderabad, Bangalore/Bengaluru",
    "experience": "4 - 7 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "Job description   - 4- 7 year experienced associate with sound knowledge on cards domain  \r\n - Should have good knowledge on testing concepts and lifecycle  \r\n - Should have experience on requirement analysis, test planning and test execution  \r\n -Should have good working knowledge on test and defect management tools  \r\n - Should have good knowledge on testing deliverables         Design & Build test harnesses for Functional Testing as SME   .        Execute test cases and Support development of automated functional and regression pack and execute        Support automation of Test Data Management for Credit cards.        Design and develop the automated solution for Sanity testing for various repeatable tests.         Soft Skills:      Excellent communication and interpersonal skills    Ability to work well in a team environment    Strong attention to detail and ability to prioritize tasks effectively    Proactive, solution-oriented approach to problem-solving.   Role: Quality Assurance and Testing - Other,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: Quality Assurance and TestingEducationUG: Any GraduatePG: Any PostgraduateKey SkillsAutomationSanity testingTest case executionInterpersonal skillsData managementFunctional testingTest executionCredit cardsDefect managementTesting",
    "logo": "./img/companies/sychron.jpg",
    "applyLink": "https://www.naukri.com/job-listings-cards-tester-v-synchron-infotech-hyderabad-secunderabad-bangalore-bengaluru-4-to-7-years-250523501841"
  },

  {
    "title": "Power Apps Developer",
    "company": "Tata Consultancy Services (TCS)",
    "location": "Hyderabad/Secunderabad, Chennai, Bangalore/ Bengaluru,Karnataka",
    "experience": "2 - 7 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "Job descriptionRole: Power apps Developer\r\nRelevant  Experience (Yrs): 2-10   year experience in Microsoft Technologies with 2+ projects as Technical   Developer in cloud based Dynamics 365 CE, Power Apps, Microsoft Flow and   Azure  Technical/Functional   Skills\r\nDesired   Skills (Must Have):Development experience should include Power Platform services, JavaScript, JSON, TypeScript, C#, HTML, .NET, Microsoft Azure, Microsoft 365, RESTful web services,        ASP.NET, and Power BIAbility design, develop, secure, and troubleshoot Power Platform   solutions using Power Apps/Flow and CDS.Strong applied knowledge of Power Platform services. Candidates have an in-depth understanding of their capabilities, boundaries, and constraintsIn depth knowledge on capabilities of Dataverse (CDS)Basic understanding of DevOps practices for Power Platform. Knowledge about O365/M365 and D365 and Azure ADExperience in pre-sales for D365 and Power PlatformExperience in administration and deployment of D365 and Power apps Excellent communication Experience in Stakeholder management in large programs Additional Skills:Implementation or Upgrade of applications to Power Apps \r\nRole: Software Development - Other,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: Software DevelopmentEducationUG: Any GraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillsPowerappsCanvasPower Platform",
    "logo": "./img/companies/tcs/TCS-1.jpg",
    "applyLink": "https://www.naukri.com/job-listings-power-apps-developer-tata-consultancy-services-tcs-hyderabad-secunderabad-chennai-bangalore-bengaluru-karnataka-2-to-7-years-260523003880"
  },
  {
    "title": "Quality Assurance Automation Engineer - Appium",
    "company": "Patch Infotech",
    "location": "Kolkata, Mumbai, Hyderabad/Secunderabad, Lucknow, Chennai, Ahmedabad, Bangalore/Bengaluru, Delhi / NCR",
    "experience": "3 - 7 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "Job descriptionWe are looking for Automation QA Engineers matching below requirement criteria :\r\n\r\n1. Must have strong experience on Appium tools with any tech stack like Java, Python or Node\r\n\r\n2. Should be good in dealing with business logics and handling complex requirements\r\n\r\n3. Should be good in basic programming skills and collections\r\n\r\n4. Should be good in building end to end frameworks around automation\r\n\r\n5. Good to have exposure in selenium.\r\n\r\nAdditional ProjectSoft Skills :\r\n\r\n- Decent enough verbal and written communication with ability to articulate problems and solutions over phone and emails.\r\n\r\n- Strong sense of urgency, with a passion for accuracy and timeliness.\r\n\r\n- Ability to work calmly in high pressure situations and manage multiple projectstasks.\r\n\r\n- Ability to work independently and possess superior skills in issue resolution.Role: Automation Developer,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: Software DevelopmentEducationUG: B.Sc in Any Specialization, B.Tech/B.E. in Any Specialization, BCA in Any SpecializationPG: Any PostgraduateDoctorate: Doctorate Not RequiredKey SkillsSkills highlighted with ‘‘ are preferred keyskillsQuality AssuranceJavaAutomation EngineerAppium toolsPython",
    "applyLink": "https://www.naukri.com/job-listings-quality-assurance-automation-engineer-appium-patch-infotech-private-limited-kolkata-mumbai-hyderabad-secunderabad-lucknow-chennai-ahmedabad-bangalore-bengaluru-delhi-ncr-3-to-7-years-040423903941"
  },

  {
    "title": "Devops Engineer",
    "company": "PwC Service Delivery Center",
    "location": "Kolkata, Hyderabad/Secunderabad, Bangalore/Bengaluru, Mumbai (All Areas)",
    "experience": "11 - 13 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "Job description  Mandatory skills:\r\nKubernetes  (Minimum 2 years of hands-on experience)Any cloud platform - AWS/Azure (GCP - Good to have & Not mandatory)CI/CD PipelinesJenkinsMicroservices ArchitectureHelm ChartsPerformance MonitoringManaging RDBMS, databasesAny APM tools(Datadog/dynatrace)NetworkingSecurity at different levelRole: IT Security - Other,Industry Type: IT Services & Consulting,Department: IT & Information Security,Employment Type: Full Time, PermanentRole Category: IT SecurityEducationUG: B.Tech/B.E. in Any SpecializationPG: M.Tech in Any Specialization, MCA in Any Specialization, MS/M.Sc(Science) in Any SpecializationKey SkillsSkills highlighted with ‘‘ are preferred keyskillskubernetesCicd PipelineMicroservicesJenkins",
    "applyLink": "https://www.naukri.com/job-listings-devops-engineer-pwc-service-delivery-center-kolkata-hyderabad-secunderabad-bangalore-bengaluru-mumbai-all-areas-11-to-13-years-160523005416"
  },
  {
    "title": "LEAD ENGINEER / DESIGNER",
    "company": "Larsen & Toubro (L&T)",
    "location": "Mumbai, Hyderabad/Secunderabad, Bangalore/Bengaluru, Mumbai (All Areas)",
    "experience": "7 - 12 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "Job descriptionGreetings From Larsen & Toubro Limited, Mumbai/India...!\r\nWe are Hiring for #Hyderabad #Mumbai #bangalore Location, OFFSHORE experience is must..!\r\n1) LEAD Engineer  Electrical\r\n2) LEAD Engineer  Mechanical\r\n3) LEAD Engineer - Structural\r\n4) LEAD Engineer – Piping\r\n5) LEAD Engineer - Process\r\nRequired Exp – 5 to 20 yrs in - Offshore oil and gas\r\n(Oil & GAS & #offshore Experience Compulsory)\r\nIf interested, Please Share updated CV on -\r\nMukteshwar.Bhaganagare@larsentoubro.com\r\nAlso Refer your friends & Connections.\r\n\r\nRole: Hardware Engineering Manager,Industry Type: Oil & Gas,Department: Engineering - Hardware & Networks,Employment Type: Full Time, PermanentRole Category: HardwareEducationUG: Graduation Not RequiredKey SkillsSkills highlighted with ‘‘ are preferred keyskillsoffshore platformsoffshoreEngineeringE3DSACSPiping DesignStructural DesignProcess EngineeringpipingoilPiping Engineeringstructural analysisStructural EngineeringgasPiping LayoutMechanical Engineering",
    "logo": "./img/companies/pwc.jpg",
    "applyLink": "https://www.naukri.com/job-listings-lead-engineer-designer-larsen-toubro-l-t-mumbai-hyderabad-secunderabad-bangalore-bengaluru-mumbai-all-areas-7-to-12-years-160523007373"
  },
  {
    "title": "Hiring For Field support Engineer (2 To 4 Years) @ Tata Elxsi.",
    "company": "Tata Elxsi",
    "location": "Hyderabad/Secunderabad, Ahmedabad, Bangalore/Bengaluru, Mumbai (All Areas)",
    "experience": "2 - 4 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "Job descriptionHiring For Field support Engineer (2 to 4 Years) @ Tata Elxsi.\r\nSkills:  DELLEMC Servers (Rack, Tower and Blade) and Chassis (VRTX and M1000e), DELLEMC Switches (PowerConnect, S-Series, N-Series etc) and DELLEMC entry level Storages such as MD14xx Series, Me- Series, NX- Series, Cisco and Brocade SAN switches.\r\nLocation: Bangalore, Hyderabad, Mumbai, Ahmedabad\r\nExperience: 2 to 4 Years\r\n Qualification: Diploma/B.E./B.Tech\r\nRoles & Responsibilities: Experience in DELL Storage, Servers, Switches Implementation, maintenance and      administration. Installation, implementation and managing DELLEMC Servers (Rack, Tower and Blade) and      Chassis (VRTX and M1000e), DELLEMC Switches (PowerConnect, S-Series,      N-Series etc) and DELLEMC entry level Storages such as MD14xx Series, Me-      Series, NX- Series etc.Managing Cisco and Brocade SAN switches, zoning with storage arrays and Dell/HP      servers. Storage terminology known SAN -FC, iSCSI and FCoE.NAS NFS, CIFS and NFS. DAS SAS      and SATA .Networking: Installation and configuration of ethernet and SAN switches (Cisco, Brocade, Dell), Knowledge of DELL EMC Networking products. Having good knowledge of VMware implementation, administration and troubleshooting. Having      good knowledge on EMC Storage Both SAN & NAS Technologies, and EMC      backup products Like EMC Avamar, Data Domain, Isilon. Having good Experience in installation and maintenance of DELL EMC products VNX, Unity, Isilon, Avamar, Centera, Data Domain, Connectrix (Brocade), Recover Point, VMAX, DMX and Vxrail.  Basic knowledge in Linux.\r\n If interested, please share the below mentioned details with your updated resume to vchandana.r@tataelxsi.co.in / chaithram@tataelxsi.co.in \r\n Total Exp: Current CTC:Expected CTC:Notice Period:Reason for Change:\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nRole: IT & Information Security - Other,Industry Type: IT Services & Consulting,Department: IT & Information Security,Employment Type: Full Time, PermanentRole Category: IT & Information Security - OtherEducationUG: Diploma in Any Specialization, B.Tech/B.E. in Any SpecializationKey SkillsSkills highlighted with ‘‘ are preferred keyskillsField EngineeringCustomer EngineeringSANNASVnxVMwareDell EMC SwitchesAvamarVxrailVMAXDell ServerDmxDell StorageBrocadeunityLinuxRecoverpointIsilonData Domain",
    "applyLink": "https://www.naukri.com/job-listings-hiring-for-field-support-engineer-2-to-4-years-tata-elxsi-tata-elxsi-hyderabad-secunderabad-ahmedabad-bangalore-bengaluru-mumbai-all-areas-2-to-4-years-170523000007"
  },
  {
    "title": "Immediate Openings For Java Developer",
    "company": "PwC Service Delivery Center",
    "location": "Kolkata, Hyderabad/Secunderabad, Bangalore/Bengaluru, Mumbai (All Areas)",
    "experience": "5 - 10 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "Job description Dear Candidate,\r\nGreetings for the day!We are delighted to inform you that we have an exciting opportunity for you to join our Java Developer team at PricewaterhouseCoopers (PwC).As part of this role, you will have the chance to work on cutting-edge technology and collaborate with a talented team of professionals. You will also be provided with extensive learning opportunities, including workshops and seminars.Feel free to refer to any of your friends or colleagues who are looking for a change.Skill: Java DeveloperExperience: 5 - 10 YearsNotice Period: Immediate Joiner onlyCurrent Location(Hybrid): Bangalore, Hyderabad, Mumbai and KolkataJob Description:MicroservicesSpring BootRestful webservicesJUnitMS-SQLJPA/HibernatePostmanSwaggerIntelliJ IDEGITJiraAdded AdvantagesXSLT/XML/XPathSoap WebservicesXML/JSON ParsersIf Interested Please share your resume to sivamurugesh.x@pwc.com Immediately\r\nTotal Work experience: Relevant Experience- Qualification:Current Company: Location: Current Fixed CTC: Variable Component: Expected CTC: Notice Period: Any offers in hand: If yes, DOJ:Regards,Sivamurugesh9786618250 Role: IT & Information Security - Other,Industry Type: Accounting / Auditing,Department: IT & Information Security,Employment Type: Full Time, PermanentRole Category: IT & Information Security - OtherEducationUG: Any GraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillsJavaHibernateSpringMicroservices",
    "applyLink": "https://www.naukri.com/job-listings-immediate-openings-for-java-developer-pwc-service-delivery-center-kolkata-hyderabad-secunderabad-bangalore-bengaluru-mumbai-all-areas-5-to-10-years-170523004942"
  },
  {
    "title": "Guidewire PC Developer",
    "company": "PwC Service Delivery Center",
    "location": "Kolkata, Hyderabad/Secunderabad, Bangalore/Bengaluru, Mumbai (All Areas)",
    "experience": "3 - 8 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "Job description  Job DescriptionHands on experience in of the Guidewire products in      Policy Center\r\n      * Well versed in one of streams  Configuration.\r\n      * Strong knowledge in Guidewire platform (Gosu scripting / UI / Data      Model)\r\n      * Good knowledge in Webservices, XML and ant script\r\n      * Experience on any database Oracle / SQL Server and well versed in SQLStrong knowledge in Guidewire platform (Gosu scripting      / UI / Data Model)Good knowledge in Web services, XMLExperience on any database Oracle / SQL Server and well      versed in SQLExperience in SCRUM Agile, prefer Certified Scrum      Master (CSM)Good knowledge of any sever such as Tomcat / JBossGood written and oral communicationExcellent analytical skillAdditional skills for Tech Lead and Senior Tech LeadsSound knowledge in software architecture and design      patternsMust have estimation, team leading, code review and      mentoring skillsWorked on at least two Guidewire implementationsGood to have skills: Thunderhead/ MuleSoft Integration experienceExposure to SCM tool such as GIT, SVN & DevOps      skillsKnowledge of any servers / containers such as Tomcat /      JBoss / WebSphereExposure to cloud technologies such as AWS, Azure ..Good written and oral communicationExcellent analytical skillScrum or SAFe or other Agile delivery waysInsurance domain knowledge\r\nIf you are interested in this position. Please share your updated resume  to bharathi.garikina@pwc.com with below details.\r\nCandidate name:Email address:Contact Number:Qualification: Total Work experience:Relavant Experiene:Current Company:Location: Current Fixed CTC:Variable Component:Expected CTC:Notice Period: Any offers in hand:If yes, DOJ:  Role: Software Development - Other,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: Software DevelopmentEducationUG: Any Graduate, B.Tech/B.E. in Any Specialization, B.Sc in Any SpecializationKey SkillsSkills highlighted with ‘‘ are preferred keyskillsconfigurationGuidewire Policy CenterGosu",
    "applyLink": "https://www.naukri.com/job-listings-guidewire-pc-developer-pwc-service-delivery-center-kolkata-hyderabad-secunderabad-bangalore-bengaluru-mumbai-all-areas-3-to-8-years-170523010717"
  },

  {
    "title": "Sap Abap Consultant",
    "company": "Rk Informatics",
    "location": "Kolkata, Mumbai,Maharashtra, Hyderabad/Secunderabad, Chennai, Bangalore/Bengaluru",
    "experience": "7 - 12 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "ABAP S4 hana Role: ERP Developer,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, Temporary/ContractualRole Category: Software DevelopmentEducationUG: Any GraduatePG: Any PostgraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillsAdobe FormsWorkflowCds Viewssap abapSAP WorkflowIDOCSBapiSap FioriWebDynProSmartformsSAP ScriptsOO ABAPWebDynPro ABAPs4 hanaAbap ObjectsRicef",
    "applyLink": "https://www.naukri.com/job-listings-sap-abap-consultant-rk-informatics-kolkata-mumbai-maharashtra-hyderabad-secunderabad-chennai-bangalore-bengaluru-7-to-12-years-250523009843"
  },
  
  {
    "title": "Functional Safety Engineer",
    "company": "Tata Elxsi",
    "location": "Hyderabad/Secunderabad, Pune, Chennai, Bangalore/Bengaluru, Trivandrum/Thiruvananthapuram",
    "experience": "3 - 8 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": " Functional SafetyExperience in functional safety management  ISO26262 Part 2Adherence to ASPICE and ISO26262 processesPreparation of DIA in agreement with customer, Prepare safety plan, safety caseExperienced in facing external audits and assessmentsLead and guide the team in functional safety activitiesDefine functional safety strategy for the projectsExperience - 3 to 12 years\r\n\r\nRole: Software Development - Other,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: Software DevelopmentEducationUG: B.Tech/B.E. in Any SpecializationPG: M.Tech in Any Specialization, MCA in Any Specialization, MS/M.Sc(Science) in Any SpecializationKey SkillsSkills highlighted with ‘‘ are preferred keyskillsISO26262ASPICE",
    "applyLink": "https://www.naukri.com/job-listings-functional-safety-engineer-tata-elxsi-hyderabad-secunderabad-pune-chennai-bangalore-bengaluru-trivandrum-thiruvananthapuram-3-to-8-years-170423007245"
  },
  {
    "title": "Pega Developers with Cosmos Exp",
    "company": "Quikr India Pvt Ltd",
    "location": "Hyderabad/ Secunderabad,Telangana, Pune,Maharashtra, Bangalore/Bengaluru",
    "experience": "5 - 10 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "Identify the tasks and responsibilities on a Pega Implementation, create and extend a Pega application Manage rules and rulesets Leverage the Enterprise Class Structure (ECS) to promote rule reuse between case types and applications, configure roles, access groups, and privileges, manage data access within an application Create wizards to configure a sequence of assignments, design applications for multiple device types and screen sizes, including mobile devices and manage integration settingsRoles Responsibilities: Ability to work independently and as a member of a team Ability to work and communicate effectively with programmers and other IT staff and non-IT functional areas Strong communication, problem-solving and leadership skills Integrate multiple technologies using Pegasystems Architect, design, and develop advanced customizations utilizing Pega Optimize solutions by performing detailed code and design reviews Disseminate best practices on solution positioning and delivery Mentor junior team members in Pega technology best practices Manage offshore resources and provide technical specs to developersKindly drop cv with details at manpreet.kour@quikr.com with below detailsJob Role: Pega developers with COSMOS expexp: 5+Location: HYD, Noida, Bangalore, PuneNotice: Immediate to 30 daysBudget: max 40 LPA\r\nRole: Full Stack Developer,Industry Type: Software Product,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: Software DevelopmentEducationUG: B.Tech/B.E. in Any SpecializationKey SkillsSkills highlighted with ‘‘ are preferred keyskillsPRPCpegaCosmos",
    "applyLink": "https://www.naukri.com/job-listings-pega-developers-with-cosmos-exp-quikr-india-pvt-ltd-hyderabad-secunderabad-telangana-pune-maharashtra-bangalore-bengaluru-5-to-10-years-190523004860"
  },
  {
    "title": "Cognizant Technology Solution is hiring For Pyspark",
    "company": "Cognizant",
    "location": "Hyderabad/ Secunderabad,Telangana, Pune,Maharashtra, Gurgaon/ Gurugram,Haryana, Chennai,Tamil Nadu, Bangalore/ Bengaluru,Karnataka",
    "experience": "4 - 9 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "PysparkRole: DeveloperDesired Experience Range: 4 to 9 yearsLocation: Chennai/Bangalore/Pune/Hyderabad/Gurgoan Notice period : Immediate- 90 Days COGNIZANT AIA PRACTICE:Cognizants AI & Analytics practice helps our clients imagine and build the Digital Economy. We are recognized by Forrester, Gartner and by other leading analyst firms as a Leader in Data and AI technologies and services, citing us as the right partner to help create a business running on AI. We do this by bringing together human insight, digital strategy, industry knowledge, design thinking, and the latest technologies to create new experiences and launch new business models.\r\n Roles & Responsibilities :\r\n The developer must have sound knowledge in Apache Spark and Python programming.Experience should be 4-6 yearsDeep experience in developing data transforming and processing tasks using pySpark such as reading data from external sources, merge data, perform data enrichment      and load in to target data destinations.Developer must have  strong experience with Hadoop technologies.Developer also needs to have hands on experience in RDBMS.Developer also needs to have  hands on experience in the shell-scripting.The Developer also needs able to do the maintenance activity like fixing the bugs by analyzing it and able to maintain the jobs flow smooth.Experience in working in the SAFe/agile model is added advantage  Benefits:Exposure to new processes and technologies.Competitive salary at par with the best in the industry.Flexible and employee friendly environment.Interested Candidates apply here :  https://forms.office.com/r/mfNYkH84X3\r\n\r\n\r\n\r\nRole: Software Development - Other,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: Software DevelopmentEducationUG: Any GraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillspyspark",
    "logo": "./img/companies/cognigent/th.jpg",
    "applyLink": "https://www.naukri.com/job-listings-cognizant-technology-solution-is-hiring-for-pyspark-cognizant-hyderabad-secunderabad-telangana-pune-maharashtra-gurgaon-gurugram-haryana-chennai-tamil-nadu-bangalore-bengaluru-karnataka-4-to-9-years-190523007797"
  },
   {
    "title": "Senior Ms Sql Database Administrator",
    "company": "Tata Consultancy Services (TCS)",
    "location": "Kolkata, Hyderabad/Secunderabad, Chennai, Bangalore/ Bengaluru,Karnataka",
    "experience": "7 - 12 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "MSSQL Server: Expert in MSSQL 2014, 2016, 2019   internals.In-depth knowledge and expertise on High   Availability/DR/ReplicationExpertise in Design, Capacity   planning and provide strategic HA\\DR solutions based on Business requirement.   Hands-on and expertise on build the   DB migration, DB upgrade and Patching.Backup and Recovery, implement SSL   encryption, TDE and good knowledge on Access management.  Expertise on database performance   analysis and troubleshooting. Responsible for Query tuning and   preventative maintenance.Expertise in Automation using tools   like (PowerShell, Puppet, Python, shell scripting, Git, REST APIs etc)Knowledge & Hands-on Experience of   Cloud Databases (AWS Preferred).DevOps Knowledge.PostgreSQLExpertise in   PostgreSQL\\Aurora database Administration (On-Prem\\AWS)Good knowledge   on Administering AWS RDS databases and databases hosted on EC2.Expertise in Design, Capacity   planning and provide strategic HA\\DR solutions based on Business requirement.   Performance analysis and troubleshooting.Experience in implementing HA\\DR\\replication,   failover and troubleshooting replication lags. Expertise in installation, Upgrade,   and patching. Backup and RecoveryHands-on in   implementing Database monitoring using shell\\Perl scripts and using tool like   Datadog. \r\n\r\n\r\n\r\nRole: Database Administrator,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: DBA / Data warehousingEducationUG: Any GraduatePG: Any PostgraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillsMSSQL DBAReplicationPerformance Tuning",
    "logo": "./img/companies/tcs/TCS-1.jpg",
    "applyLink": "https://www.naukri.com/job-listings-senior-ms-sql-database-administrator-tata-consultancy-services-tcs-kolkata-hyderabad-secunderabad-chennai-bangalore-bengaluru-karnataka-7-to-12-years-250523005387"
  },
  {
    "title": "Cognizant Technology Solution is hiring For Pyspark",
    "company": "Cognizant",
    "location": "Hyderabad/ Secunderabad,Telangana, Pune,Maharashtra, Gurgaon/ Gurugram,Haryana, Chennai,Tamil Nadu, Bangalore/ Bengaluru,Karnataka",
    "experience": "4 - 9 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "PysparkRole: DeveloperDesired Experience Range: 4 to 9 yearsLocation: Chennai/Bangalore/Pune/Hyderabad/Gurgoan Notice period : Immediate- 90 Days COGNIZANT AIA PRACTICE:Cognizants AI & Analytics practice helps our clients imagine and build the Digital Economy. We are recognized by Forrester, Gartner and by other leading analyst firms as a Leader in Data and AI technologies and services, citing us as the right partner to help create a business running on AI. We do this by bringing together human insight, digital strategy, industry knowledge, design thinking, and the latest technologies to create new experiences and launch new business models.\r\n Roles & Responsibilities :\r\n The developer must have sound knowledge in Apache Spark and Python programming.Experience should be 4-6 yearsDeep experience in developing data transforming and processing tasks using pySpark such as reading data from external sources, merge data, perform data enrichment      and load in to target data destinations.Developer must have  strong experience with Hadoop technologies.Developer also needs to have hands on experience in RDBMS.Developer also needs to have  hands on experience in the shell-scripting.The Developer also needs able to do the maintenance activity like fixing the bugs by analyzing it and able to maintain the jobs flow smooth.Experience in working in the SAFe/agile model is added advantage  Benefits:Exposure to new processes and technologies.Competitive salary at par with the best in the industry.Flexible and employee friendly environment.Interested Candidates apply here :  https://forms.office.com/r/mfNYkH84X3\r\n\r\n\r\n\r\nRole: Software Development - Other,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: Software DevelopmentEducationUG: Any GraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillspyspark",
    "logo": "./img/companies/cognigent/th.jpg",
    "applyLink": "https://www.naukri.com/job-listings-cognizant-technology-solution-is-hiring-for-pyspark-cognizant-hyderabad-secunderabad-telangana-pune-maharashtra-gurgaon-gurugram-haryana-chennai-tamil-nadu-bangalore-bengaluru-karnataka-4-to-9-years-190523007797"
  },
   {
    "title": "Senior Ms Sql Database Administrator",
    "company": "Tata Consultancy Services (TCS)",
    "location": "Kolkata, Hyderabad/Secunderabad, Chennai, Bangalore/ Bengaluru,Karnataka",
    "experience": "7 - 12 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "MSSQL Server: Expert in MSSQL 2014, 2016, 2019   internals.In-depth knowledge and expertise on High   Availability/DR/ReplicationExpertise in Design, Capacity   planning and provide strategic HA\\DR solutions based on Business requirement.   Hands-on and expertise on build the   DB migration, DB upgrade and Patching.Backup and Recovery, implement SSL   encryption, TDE and good knowledge on Access management.  Expertise on database performance   analysis and troubleshooting. Responsible for Query tuning and   preventative maintenance.Expertise in Automation using tools   like (PowerShell, Puppet, Python, shell scripting, Git, REST APIs etc)Knowledge & Hands-on Experience of   Cloud Databases (AWS Preferred).DevOps Knowledge.PostgreSQLExpertise in   PostgreSQL\\Aurora database Administration (On-Prem\\AWS)Good knowledge   on Administering AWS RDS databases and databases hosted on EC2.Expertise in Design, Capacity   planning and provide strategic HA\\DR solutions based on Business requirement.   Performance analysis and troubleshooting.Experience in implementing HA\\DR\\replication,   failover and troubleshooting replication lags. Expertise in installation, Upgrade,   and patching. Backup and RecoveryHands-on in   implementing Database monitoring using shell\\Perl scripts and using tool like   Datadog. \r\n\r\n\r\n\r\nRole: Database Administrator,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: DBA / Data warehousingEducationUG: Any GraduatePG: Any PostgraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillsMSSQL DBAReplicationPerformance Tuning",
    "logo": "./img/companies/tcs/TCS-1.jpg",
    "applyLink": "https://www.naukri.com/job-listings-senior-ms-sql-database-administrator-tata-consultancy-services-tcs-kolkata-hyderabad-secunderabad-chennai-bangalore-bengaluru-karnataka-7-to-12-years-250523005387"
  },
  {
    "title": "Cognizant Technology Solution is hiring For Pyspark",
    "company": "Cognizant",
    "location": "Hyderabad/ Secunderabad,Telangana, Pune,Maharashtra, Gurgaon/ Gurugram,Haryana, Chennai,Tamil Nadu, Bangalore/ Bengaluru,Karnataka",
    "experience": "4 - 9 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "PysparkRole: DeveloperDesired Experience Range: 4 to 9 yearsLocation: Chennai/Bangalore/Pune/Hyderabad/Gurgoan Notice period : Immediate- 90 Days COGNIZANT AIA PRACTICE:Cognizants AI & Analytics practice helps our clients imagine and build the Digital Economy. We are recognized by Forrester, Gartner and by other leading analyst firms as a Leader in Data and AI technologies and services, citing us as the right partner to help create a business running on AI. We do this by bringing together human insight, digital strategy, industry knowledge, design thinking, and the latest technologies to create new experiences and launch new business models.\r\n Roles & Responsibilities :\r\n The developer must have sound knowledge in Apache Spark and Python programming.Experience should be 4-6 yearsDeep experience in developing data transforming and processing tasks using pySpark such as reading data from external sources, merge data, perform data enrichment      and load in to target data destinations.Developer must have  strong experience with Hadoop technologies.Developer also needs to have hands on experience in RDBMS.Developer also needs to have  hands on experience in the shell-scripting.The Developer also needs able to do the maintenance activity like fixing the bugs by analyzing it and able to maintain the jobs flow smooth.Experience in working in the SAFe/agile model is added advantage  Benefits:Exposure to new processes and technologies.Competitive salary at par with the best in the industry.Flexible and employee friendly environment.Interested Candidates apply here :  https://forms.office.com/r/mfNYkH84X3\r\n\r\n\r\n\r\nRole: Software Development - Other,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: Software DevelopmentEducationUG: Any GraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillspyspark",
    "logo": "./img/companies/cognigent/th.jpg",
    "applyLink": "https://www.naukri.com/job-listings-cognizant-technology-solution-is-hiring-for-pyspark-cognizant-hyderabad-secunderabad-telangana-pune-maharashtra-gurgaon-gurugram-haryana-chennai-tamil-nadu-bangalore-bengaluru-karnataka-4-to-9-years-190523007797"
  },
   {
    "title": "Senior Ms Sql Database Administrator",
    "company": "Tata Consultancy Services (TCS)",
    "location": "Kolkata, Hyderabad/Secunderabad, Chennai, Bangalore/ Bengaluru,Karnataka",
    "experience": "7 - 12 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "MSSQL Server: Expert in MSSQL 2014, 2016, 2019   internals.In-depth knowledge and expertise on High   Availability/DR/ReplicationExpertise in Design, Capacity   planning and provide strategic HA\\DR solutions based on Business requirement.   Hands-on and expertise on build the   DB migration, DB upgrade and Patching.Backup and Recovery, implement SSL   encryption, TDE and good knowledge on Access management.  Expertise on database performance   analysis and troubleshooting. Responsible for Query tuning and   preventative maintenance.Expertise in Automation using tools   like (PowerShell, Puppet, Python, shell scripting, Git, REST APIs etc)Knowledge & Hands-on Experience of   Cloud Databases (AWS Preferred).DevOps Knowledge.PostgreSQLExpertise in   PostgreSQL\\Aurora database Administration (On-Prem\\AWS)Good knowledge   on Administering AWS RDS databases and databases hosted on EC2.Expertise in Design, Capacity   planning and provide strategic HA\\DR solutions based on Business requirement.   Performance analysis and troubleshooting.Experience in implementing HA\\DR\\replication,   failover and troubleshooting replication lags. Expertise in installation, Upgrade,   and patching. Backup and RecoveryHands-on in   implementing Database monitoring using shell\\Perl scripts and using tool like   Datadog. \r\n\r\n\r\n\r\nRole: Database Administrator,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: DBA / Data warehousingEducationUG: Any GraduatePG: Any PostgraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillsMSSQL DBAReplicationPerformance Tuning",
    "logo": "./img/companies/tcs/TCS-1.jpg",
    "applyLink": "https://www.naukri.com/job-listings-senior-ms-sql-database-administrator-tata-consultancy-services-tcs-kolkata-hyderabad-secunderabad-chennai-bangalore-bengaluru-karnataka-7-to-12-years-250523005387"
  },
  {
    "title": "Cognizant Technology Solution is hiring For Pyspark",
    "company": "Cognizant",
    "location": "Hyderabad/ Secunderabad,Telangana, Pune,Maharashtra, Gurgaon/ Gurugram,Haryana, Chennai,Tamil Nadu, Bangalore/ Bengaluru,Karnataka",
    "experience": "4 - 9 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "PysparkRole: DeveloperDesired Experience Range: 4 to 9 yearsLocation: Chennai/Bangalore/Pune/Hyderabad/Gurgoan Notice period : Immediate- 90 Days COGNIZANT AIA PRACTICE:Cognizants AI & Analytics practice helps our clients imagine and build the Digital Economy. We are recognized by Forrester, Gartner and by other leading analyst firms as a Leader in Data and AI technologies and services, citing us as the right partner to help create a business running on AI. We do this by bringing together human insight, digital strategy, industry knowledge, design thinking, and the latest technologies to create new experiences and launch new business models.\r\n Roles & Responsibilities :\r\n The developer must have sound knowledge in Apache Spark and Python programming.Experience should be 4-6 yearsDeep experience in developing data transforming and processing tasks using pySpark such as reading data from external sources, merge data, perform data enrichment      and load in to target data destinations.Developer must have  strong experience with Hadoop technologies.Developer also needs to have hands on experience in RDBMS.Developer also needs to have  hands on experience in the shell-scripting.The Developer also needs able to do the maintenance activity like fixing the bugs by analyzing it and able to maintain the jobs flow smooth.Experience in working in the SAFe/agile model is added advantage  Benefits:Exposure to new processes and technologies.Competitive salary at par with the best in the industry.Flexible and employee friendly environment.Interested Candidates apply here :  https://forms.office.com/r/mfNYkH84X3\r\n\r\n\r\n\r\nRole: Software Development - Other,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: Software DevelopmentEducationUG: Any GraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillspyspark",
    "logo": "./img/companies/cognigent/th.jpg",
    "applyLink": "https://www.naukri.com/job-listings-cognizant-technology-solution-is-hiring-for-pyspark-cognizant-hyderabad-secunderabad-telangana-pune-maharashtra-gurgaon-gurugram-haryana-chennai-tamil-nadu-bangalore-bengaluru-karnataka-4-to-9-years-190523007797"
  },
   {
    "title": "Senior Ms Sql Database Administrator",
    "company": "Tata Consultancy Services (TCS)",
    "location": "Kolkata, Hyderabad/Secunderabad, Chennai, Bangalore/ Bengaluru,Karnataka",
    "experience": "7 - 12 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "MSSQL Server: Expert in MSSQL 2014, 2016, 2019   internals.In-depth knowledge and expertise on High   Availability/DR/ReplicationExpertise in Design, Capacity   planning and provide strategic HA\\DR solutions based on Business requirement.   Hands-on and expertise on build the   DB migration, DB upgrade and Patching.Backup and Recovery, implement SSL   encryption, TDE and good knowledge on Access management.  Expertise on database performance   analysis and troubleshooting. Responsible for Query tuning and   preventative maintenance.Expertise in Automation using tools   like (PowerShell, Puppet, Python, shell scripting, Git, REST APIs etc)Knowledge & Hands-on Experience of   Cloud Databases (AWS Preferred).DevOps Knowledge.PostgreSQLExpertise in   PostgreSQL\\Aurora database Administration (On-Prem\\AWS)Good knowledge   on Administering AWS RDS databases and databases hosted on EC2.Expertise in Design, Capacity   planning and provide strategic HA\\DR solutions based on Business requirement.   Performance analysis and troubleshooting.Experience in implementing HA\\DR\\replication,   failover and troubleshooting replication lags. Expertise in installation, Upgrade,   and patching. Backup and RecoveryHands-on in   implementing Database monitoring using shell\\Perl scripts and using tool like   Datadog. \r\n\r\n\r\n\r\nRole: Database Administrator,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: DBA / Data warehousingEducationUG: Any GraduatePG: Any PostgraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillsMSSQL DBAReplicationPerformance Tuning",
    "logo": "./img/companies/tcs/TCS-1.jpg",
    "applyLink": "https://www.naukri.com/job-listings-senior-ms-sql-database-administrator-tata-consultancy-services-tcs-kolkata-hyderabad-secunderabad-chennai-bangalore-bengaluru-karnataka-7-to-12-years-250523005387"
  },
  {
    "title": "Cognizant Technology Solution is hiring For Pyspark",
    "company": "Cognizant",
    "location": "Hyderabad/ Secunderabad,Telangana, Pune,Maharashtra, Gurgaon/ Gurugram,Haryana, Chennai,Tamil Nadu, Bangalore/ Bengaluru,Karnataka",
    "experience": "4 - 9 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "PysparkRole: DeveloperDesired Experience Range: 4 to 9 yearsLocation: Chennai/Bangalore/Pune/Hyderabad/Gurgoan Notice period : Immediate- 90 Days COGNIZANT AIA PRACTICE:Cognizants AI & Analytics practice helps our clients imagine and build the Digital Economy. We are recognized by Forrester, Gartner and by other leading analyst firms as a Leader in Data and AI technologies and services, citing us as the right partner to help create a business running on AI. We do this by bringing together human insight, digital strategy, industry knowledge, design thinking, and the latest technologies to create new experiences and launch new business models.\r\n Roles & Responsibilities :\r\n The developer must have sound knowledge in Apache Spark and Python programming.Experience should be 4-6 yearsDeep experience in developing data transforming and processing tasks using pySpark such as reading data from external sources, merge data, perform data enrichment      and load in to target data destinations.Developer must have  strong experience with Hadoop technologies.Developer also needs to have hands on experience in RDBMS.Developer also needs to have  hands on experience in the shell-scripting.The Developer also needs able to do the maintenance activity like fixing the bugs by analyzing it and able to maintain the jobs flow smooth.Experience in working in the SAFe/agile model is added advantage  Benefits:Exposure to new processes and technologies.Competitive salary at par with the best in the industry.Flexible and employee friendly environment.Interested Candidates apply here :  https://forms.office.com/r/mfNYkH84X3\r\n\r\n\r\n\r\nRole: Software Development - Other,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: Software DevelopmentEducationUG: Any GraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillspyspark",
    "logo": "./img/companies/cognigent/th.jpg",
    "applyLink": "https://www.naukri.com/job-listings-cognizant-technology-solution-is-hiring-for-pyspark-cognizant-hyderabad-secunderabad-telangana-pune-maharashtra-gurgaon-gurugram-haryana-chennai-tamil-nadu-bangalore-bengaluru-karnataka-4-to-9-years-190523007797"
  },
   {
    "title": "Senior Ms Sql Database Administrator",
    "company": "Tata Consultancy Services (TCS)",
    "location": "Kolkata, Hyderabad/Secunderabad, Chennai, Bangalore/ Bengaluru,Karnataka",
    "experience": "7 - 12 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "MSSQL Server: Expert in MSSQL 2014, 2016, 2019   internals.In-depth knowledge and expertise on High   Availability/DR/ReplicationExpertise in Design, Capacity   planning and provide strategic HA\\DR solutions based on Business requirement.   Hands-on and expertise on build the   DB migration, DB upgrade and Patching.Backup and Recovery, implement SSL   encryption, TDE and good knowledge on Access management.  Expertise on database performance   analysis and troubleshooting. Responsible for Query tuning and   preventative maintenance.Expertise in Automation using tools   like (PowerShell, Puppet, Python, shell scripting, Git, REST APIs etc)Knowledge & Hands-on Experience of   Cloud Databases (AWS Preferred).DevOps Knowledge.PostgreSQLExpertise in   PostgreSQL\\Aurora database Administration (On-Prem\\AWS)Good knowledge   on Administering AWS RDS databases and databases hosted on EC2.Expertise in Design, Capacity   planning and provide strategic HA\\DR solutions based on Business requirement.   Performance analysis and troubleshooting.Experience in implementing HA\\DR\\replication,   failover and troubleshooting replication lags. Expertise in installation, Upgrade,   and patching. Backup and RecoveryHands-on in   implementing Database monitoring using shell\\Perl scripts and using tool like   Datadog. \r\n\r\n\r\n\r\nRole: Database Administrator,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: DBA / Data warehousingEducationUG: Any GraduatePG: Any PostgraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillsMSSQL DBAReplicationPerformance Tuning",
    "logo": "./img/companies/tcs/TCS-1.jpg",
    "applyLink": "https://www.naukri.com/job-listings-senior-ms-sql-database-administrator-tata-consultancy-services-tcs-kolkata-hyderabad-secunderabad-chennai-bangalore-bengaluru-karnataka-7-to-12-years-250523005387"
  },
  {
    "title": "Cognizant Technology Solution is hiring For Pyspark",
    "company": "Cognizant",
    "location": "Hyderabad/ Secunderabad,Telangana, Pune,Maharashtra, Gurgaon/ Gurugram,Haryana, Chennai,Tamil Nadu, Bangalore/ Bengaluru,Karnataka",
    "experience": "4 - 9 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "PysparkRole: DeveloperDesired Experience Range: 4 to 9 yearsLocation: Chennai/Bangalore/Pune/Hyderabad/Gurgoan Notice period : Immediate- 90 Days COGNIZANT AIA PRACTICE:Cognizants AI & Analytics practice helps our clients imagine and build the Digital Economy. We are recognized by Forrester, Gartner and by other leading analyst firms as a Leader in Data and AI technologies and services, citing us as the right partner to help create a business running on AI. We do this by bringing together human insight, digital strategy, industry knowledge, design thinking, and the latest technologies to create new experiences and launch new business models.\r\n Roles & Responsibilities :\r\n The developer must have sound knowledge in Apache Spark and Python programming.Experience should be 4-6 yearsDeep experience in developing data transforming and processing tasks using pySpark such as reading data from external sources, merge data, perform data enrichment      and load in to target data destinations.Developer must have  strong experience with Hadoop technologies.Developer also needs to have hands on experience in RDBMS.Developer also needs to have  hands on experience in the shell-scripting.The Developer also needs able to do the maintenance activity like fixing the bugs by analyzing it and able to maintain the jobs flow smooth.Experience in working in the SAFe/agile model is added advantage  Benefits:Exposure to new processes and technologies.Competitive salary at par with the best in the industry.Flexible and employee friendly environment.Interested Candidates apply here :  https://forms.office.com/r/mfNYkH84X3\r\n\r\n\r\n\r\nRole: Software Development - Other,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: Software DevelopmentEducationUG: Any GraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillspyspark",
    "logo": "./img/companies/cognigent/th.jpg",
    "applyLink": "https://www.naukri.com/job-listings-cognizant-technology-solution-is-hiring-for-pyspark-cognizant-hyderabad-secunderabad-telangana-pune-maharashtra-gurgaon-gurugram-haryana-chennai-tamil-nadu-bangalore-bengaluru-karnataka-4-to-9-years-190523007797"
  },
   {
    "title": "Senior Ms Sql Database Administrator",
    "company": "Tata Consultancy Services (TCS)",
    "location": "Kolkata, Hyderabad/Secunderabad, Chennai, Bangalore/ Bengaluru,Karnataka",
    "experience": "7 - 12 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "MSSQL Server: Expert in MSSQL 2014, 2016, 2019   internals.In-depth knowledge and expertise on High   Availability/DR/ReplicationExpertise in Design, Capacity   planning and provide strategic HA\\DR solutions based on Business requirement.   Hands-on and expertise on build the   DB migration, DB upgrade and Patching.Backup and Recovery, implement SSL   encryption, TDE and good knowledge on Access management.  Expertise on database performance   analysis and troubleshooting. Responsible for Query tuning and   preventative maintenance.Expertise in Automation using tools   like (PowerShell, Puppet, Python, shell scripting, Git, REST APIs etc)Knowledge & Hands-on Experience of   Cloud Databases (AWS Preferred).DevOps Knowledge.PostgreSQLExpertise in   PostgreSQL\\Aurora database Administration (On-Prem\\AWS)Good knowledge   on Administering AWS RDS databases and databases hosted on EC2.Expertise in Design, Capacity   planning and provide strategic HA\\DR solutions based on Business requirement.   Performance analysis and troubleshooting.Experience in implementing HA\\DR\\replication,   failover and troubleshooting replication lags. Expertise in installation, Upgrade,   and patching. Backup and RecoveryHands-on in   implementing Database monitoring using shell\\Perl scripts and using tool like   Datadog. \r\n\r\n\r\n\r\nRole: Database Administrator,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: DBA / Data warehousingEducationUG: Any GraduatePG: Any PostgraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillsMSSQL DBAReplicationPerformance Tuning",
    "logo": "./img/companies/tcs/TCS-1.jpg",
    "applyLink": "https://www.naukri.com/job-listings-senior-ms-sql-database-administrator-tata-consultancy-services-tcs-kolkata-hyderabad-secunderabad-chennai-bangalore-bengaluru-karnataka-7-to-12-years-250523005387"
  },
  {
    "title": "Cognizant Technology Solution is hiring For Pyspark",
    "company": "Cognizant",
    "location": "Hyderabad/ Secunderabad,Telangana, Pune,Maharashtra, Gurgaon/ Gurugram,Haryana, Chennai,Tamil Nadu, Bangalore/ Bengaluru,Karnataka",
    "experience": "4 - 9 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "PysparkRole: DeveloperDesired Experience Range: 4 to 9 yearsLocation: Chennai/Bangalore/Pune/Hyderabad/Gurgoan Notice period : Immediate- 90 Days COGNIZANT AIA PRACTICE:Cognizants AI & Analytics practice helps our clients imagine and build the Digital Economy. We are recognized by Forrester, Gartner and by other leading analyst firms as a Leader in Data and AI technologies and services, citing us as the right partner to help create a business running on AI. We do this by bringing together human insight, digital strategy, industry knowledge, design thinking, and the latest technologies to create new experiences and launch new business models.\r\n Roles & Responsibilities :\r\n The developer must have sound knowledge in Apache Spark and Python programming.Experience should be 4-6 yearsDeep experience in developing data transforming and processing tasks using pySpark such as reading data from external sources, merge data, perform data enrichment      and load in to target data destinations.Developer must have  strong experience with Hadoop technologies.Developer also needs to have hands on experience in RDBMS.Developer also needs to have  hands on experience in the shell-scripting.The Developer also needs able to do the maintenance activity like fixing the bugs by analyzing it and able to maintain the jobs flow smooth.Experience in working in the SAFe/agile model is added advantage  Benefits:Exposure to new processes and technologies.Competitive salary at par with the best in the industry.Flexible and employee friendly environment.Interested Candidates apply here :  https://forms.office.com/r/mfNYkH84X3\r\n\r\n\r\n\r\nRole: Software Development - Other,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: Software DevelopmentEducationUG: Any GraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillspyspark",
    "logo": "./img/companies/cognigent/th.jpg",
    "applyLink": "https://www.naukri.com/job-listings-cognizant-technology-solution-is-hiring-for-pyspark-cognizant-hyderabad-secunderabad-telangana-pune-maharashtra-gurgaon-gurugram-haryana-chennai-tamil-nadu-bangalore-bengaluru-karnataka-4-to-9-years-190523007797"
  },
   {
    "title": "Senior Ms Sql Database Administrator",
    "company": "Tata Consultancy Services (TCS)",
    "location": "Kolkata, Hyderabad/Secunderabad, Chennai, Bangalore/ Bengaluru,Karnataka",
    "experience": "7 - 12 years",
    "salary":"",
    "skills":"",
    "responsibilities":"",
    "description": "MSSQL Server: Expert in MSSQL 2014, 2016, 2019   internals.In-depth knowledge and expertise on High   Availability/DR/ReplicationExpertise in Design, Capacity   planning and provide strategic HA\\DR solutions based on Business requirement.   Hands-on and expertise on build the   DB migration, DB upgrade and Patching.Backup and Recovery, implement SSL   encryption, TDE and good knowledge on Access management.  Expertise on database performance   analysis and troubleshooting. Responsible for Query tuning and   preventative maintenance.Expertise in Automation using tools   like (PowerShell, Puppet, Python, shell scripting, Git, REST APIs etc)Knowledge & Hands-on Experience of   Cloud Databases (AWS Preferred).DevOps Knowledge.PostgreSQLExpertise in   PostgreSQL\\Aurora database Administration (On-Prem\\AWS)Good knowledge   on Administering AWS RDS databases and databases hosted on EC2.Expertise in Design, Capacity   planning and provide strategic HA\\DR solutions based on Business requirement.   Performance analysis and troubleshooting.Experience in implementing HA\\DR\\replication,   failover and troubleshooting replication lags. Expertise in installation, Upgrade,   and patching. Backup and RecoveryHands-on in   implementing Database monitoring using shell\\Perl scripts and using tool like   Datadog. \r\n\r\n\r\n\r\nRole: Database Administrator,Industry Type: IT Services & Consulting,Department: Engineering - Software & QA,Employment Type: Full Time, PermanentRole Category: DBA / Data warehousingEducationUG: Any GraduatePG: Any PostgraduateKey SkillsSkills highlighted with ‘‘ are preferred keyskillsMSSQL DBAReplicationPerformance Tuning",
    "logo": "./img/companies/tcs/TCS-1.jpg",
    "applyLink": "https://www.naukri.com/job-listings-senior-ms-sql-database-administrator-tata-consultancy-services-tcs-kolkata-hyderabad-secunderabad-chennai-bangalore-bengaluru-karnataka-7-to-12-years-250523005387"
  },

]